### ISSUE TITLE
Default web.xml for custom instances

### ISSUE THREAD

**Issue by predicador37** [lbetz/puppet-tomcat#1]
I think it should be nice to have the default web.xml file automatically copied into the conf folders of the created tomcat instances (if any). Some apps won't work without one.

At least I've checked it doesn't exist in Debian Wheezy, using tomcat7.

**Comment by lbetz** [comment]
Now is implemented, in the next branch. My tomcat7 for wheezy has a web.xml. (deb http://ftp.debian.org/debian/ wheezy main)

**Comment by predicador37** [comment]
Yes, mine too; I meant that the module didn't copy the file to the instances config folder. Much better now!
