### ISSUE TITLE
Instance folders permissions

### ISSUE THREAD

**Issue by predicador37** [lbetz/puppet-tomcat#2]
I was wondering why is the user root the owner of the webapps folder, for example. This way tomcat user does not have permissions to automatically deploy war files...

I think this should be revised or, at least, the posibility to change it should be offered.

**Comment by lbetz** [comment]
You're right. I think that's a bug. I fixed it, set the ownership for group to the group tomcat is running. I did the same for the work directory. Fixed in next and master branch.

**Comment by predicador37** [comment]
Nice, much better!
By the way, great work with this module; I tried puppetlabs first, but the Augeas requirement was not fullfilled easily by Debian Wheezy. Your module satisfies all my needs, and with this little improvements it'll work flawleess.
