### ISSUE TITLE
Multiple instances in CentOS server wont work

### ISSUE THREAD

**Issue by predicador37** [lbetz/puppet-tomcat#4]
I've been trying using multiple tomcat7 instances both on Debian and Centos. It works nice with Debian distributions, but I've found some problems with Centos.
I think it's related to the tomcat init scripts tomcat-{$name} of the instances. It seems like these scripts are not properly modified in order to include the instance parameters (name of the instance, ports, paths, etc.)
Have you successfully tested multiple instances in Redhat families? Maybe I'm missing something?

**Comment by predicador37** [comment]
Ok, I think I know which the problem is. When /etc/init.d/tomcat-{$name} calls /usr/sbin/tomcat, the latter overwrites instance configuration calling general tomcat config file:

```
# Get the tomcat config (use this for environment specific settings)
if [ -z "${TOMCAT_CFG}" ]; then
      TOMCAT_CFG="/etc/tomcat/tomcat.conf"
fi
if [ -r "$TOMCAT_CFG" ]; then
      . $TOMCAT_CFG
fi
```

Now I guess I'll have to figure out which would be the better fix... Perhaps providing fixed /usr/sbin/tomcat script with puppet?

**Comment by predicador37** [comment]
lol, it seems it's a known bug 
https://bugzilla.redhat.com/show_bug.cgi?id=1080195

**Comment by lbetz** [comment]
A workaround for the actually code,  use the setenv parameter of tomcat::server like setenv => ['TOMCAT_CFG=/etc/sysconfig/tomcat-TITLE'] where TITLE has to be replaced with the instance name. 
My idea is to set TOMCAT_CFG inside the sysconfig template. Ok, so sysconfig will be read twice but so what. 
Why? Because I'm not a fan to make code changes of packages or bug fixes with puppet.

**Comment by lbetz** [comment]
done.

Clear that sysconfig overrides tomcat.conf

**Comment by lbetz** [comment]
done in master/next branch.

Clear that sysconfig overrides tomcat.conf

**Comment by predicador37** [comment]
That's a better solution than modifying the provided file. I've tested your fixes too and they works like a charm. Thanks a lot!

**Comment by lbetz** [comment]
Your welcome! And thx 4 the feedback….
