### ISSUE TITLE
tomcat7 user cannot recreate work directory

### ISSUE THREAD

**Issue by predicador37** [lbetz/puppet-tomcat#8]
I'm not sure if this is an issue or not, but atm $CATALINA_BASE directory is owned by root:root. This prevents tomcat7 user to, for example, recreate the work directory if deleted (in order to clean cached files). This is happening in Debian 7.X with Tomcat7 using multiple instances (deployed in /var/tomcat/[instance_name]).

**Comment by lbetz** [comment]
Ok, I tried to look about the distro handle it and your right, CATALINA_BASE on RedHat belong to group tomcat with write permission. So I will fix it. On Debian it's belong root:root... but I think it's ok to change it.

**Comment by lbetz** [comment]
Oh, sorry on Debian it's a link to /var/cache/tomcatX and then it's the same, group tomcat with write permissions!

**Comment by lbetz** [comment]
fixed in branch next

**Comment by lbetz** [comment]
... and master branch.
